### ISSUE TITLE
Gang Glitch

### ISSUE THREAD

**Issue by MaxParallel** [EasysAltisLife/Easys-Altis-Life#80] opened 2016-02-19 19:02 UTC
Even after you leave a gang and try to make a new one, it says that you are still active in a gang. You then are not able to access your gang tab, until you have re-logged. After re-logging, you are then back in your old group.

**Comment by imthatguyhere** [comment] 2016-02-20 21:04
Duplicate of #44 please do as it says there. 

This happens if you have joined the gang originally multiple times.you only get removed one time and are stuck in the old gang. Posting on our forum's help desk with your playerid and what gang you want to stay in if any is your best bet.

**Closed as completed by imthatguyhere** 2016-02-20 21:04 UTC
